### PR TITLE
Fix markdown formatting in Telegram links

### LINKED ISSUE #56: [BUG] Fix Telegram markdown formatting in link labels
**Describe the bug**
Telegram doesn't support bold/italic formatting within links (or links within bold/italic formatting) and just displays the raw markdown text (or raw link) instead.

**To Reproduce**
1. Subscribe to any game
2. Look at the Telegram notifications
3. See the bugged link / markdown formatting

**Expected behavior**
Links should always be preferred over bold/italic formatting. The markdown text should be cut out within links. Outside of links, the link formatting should be "cut out" of the bold/italic formatting, for example:
- `[*link*](url)*` should turn into
`[link](url)`
- `*test text with a [link](url) as an example*` should turn into
`*test text with a* [link](url) *as an example*`

**Screenshots**
The problem mostly occurs for the headlines:
Link formatting in Telegram

**Clients:**
The clients affected by the bug:
 - [ ] Discord
 - [x] Telegram

### PR DESCRIPTION
**Pull request by TimJentzsch**
Fix #56 (Markdown formatting  in Telegram links).

### CODE REVIEW

File: src/bot_telegram.ts [hunk 1]
```diff
@@ -154,13 +154,29 @@ export default class TelegramBot extends BotClient {
...
     markdown = markdown.replace(/\*\*(.+)\*\*/g, '*$1*');
+    // Formatting with Links
+    markdown = markdown.replace(/\*(.*)[ \t]*\[(.*)\]\((.*)\)[ \t]*(.*)\*/g, '*$1* [$2]($3) *$4*');
+    markdown = markdown.replace(
+      /__(.*)[ \t]*\[(.*)\]\((.*)\)[ \t]*(.*)__/g,
+      '__$1__ [$2]($3) __$4__',
+    );
+
+    markdown = markdown.replace(/\[\*(.*)\*\]\((.*)\)/g, '[$1]($2)');
+    markdown = markdown.replace(/\[__(.*)__\]\((.*)\)/g, '[$1]($2)');
```
Comment (zachkont) [inline src/bot_telegram.ts]: I can see some regular expressions being reused. Do you think it would make sense to standardize them, and perhaps even split them to meaningful components which can be combined to make a specific regex? 
For example: `(.*)` is pretty standard and could be named something and reused. 

Not very sure about the splitting part, but naming regexes sounds like a good idea. For example we can have:
``` typescript
linkRegex = /\[\*(.*)\*\]\((.*)\)/g;
markdown = markdown.replace(linkRegex, '[$1]($2)');
```
or something along these lines

Comment (TimJentzsch) [reply src/bot_telegram.ts]: That's a good point and would probably make bugfixing easier as well.
However, I don't think you can put a regex in another regex, so we would have to use strings for everything and then convert those to regexes in the replace method. But that's probably still better than the current approach.

Comment (TimJentzsch) [reply src/bot_telegram.ts]: I will fix this in a seperate issue (#60).
